project_id = "aahxmxgmmgfymhenlqdy"

[functions.create-test-users]
verify_jwt = false

[functions.create-payment-preference]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.send-event-qr-emails]
verify_jwt = false

[functions.create-stripe-payment]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.transform-photo-ai]
verify_jwt = false

[functions.download-album-zip]
verify_jwt = false

[functions.decrement-courtesy-counter]
verify_jwt = false
